### ISSUE TITLE
CT Corner overlap on left edge

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/under-pressure#151]
```
under-pressure : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/under-pressure/under-pressure_en.html?continuousTest=%7B%22test%22%3A%5B%22under-pressure%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1662721214770%22%2C%22timestamp%22%3A1662728697920%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Corner overlap on left edge
Error: Assertion failed: Corner overlap on left edge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/assert/js/assert.js:28:13)
at assert (Shape.js:2037:14)
at roundedRectangleWithRadii (RectangularButton.ts:215:15)
at createButtonShape (RectangularButton.ts:186:33)
at callback (Multilink.ts:128:6)
at (Multilink.ts:184:11)
at multilink (RectangularButton.ts:180:14)
at (RectangularPushButton.ts:53:4)
at (ComboBoxButton.ts:207:4)
at (ComboBox.ts:260:18)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 5:00:14 AM

----------------------------------

under-pressure : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/under-pressure/under-pressure_en.html?continuousTest=%7B%22test%22%3A%5B%22under-pressure%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1662721214770%22%2C%22timestamp%22%3A1662735150693%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Corner overlap on left edge
Error: Assertion failed: Corner overlap on left edge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/assert/js/assert.js:28:13)
at assert (Shape.js:2037:14)
at roundedRectangleWithRadii (RectangularButton.ts:215:15)
at createButtonShape (RectangularButton.ts:186:33)
at callback (Multilink.ts:128:6)
at (Multilink.ts:184:11)
at multilink (RectangularButton.ts:180:14)
at (RectangularPushButton.ts:53:4)
at (ComboBoxButton.ts:207:4)
at (ComboBox.ts:260:18)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 5:00:14 AM
```

**Comment by samreid** [comment]
I shared this with @jbphet and and @zepumph.  @jbphet volunteered to review, but we also want to discuss it with @jonathanolson.

**Comment by jonathanolson** [comment]
I'm a bit uncomfortable with this, is that exact fix something we'd be using in EVERY place we call this function? Why not just outlaw calling it with invalid parameters, and adjust call sites to not call it in this way?

**Comment by samreid** [comment]
I agree and that is what I tried initially. Following these steps:

* Reverting the above commit
* Running under pressure with ?stringTest=xss

We get the stack trace in the top comment https://github.com/phetsims/under-pressure/issues/151#issue-1368079332

The ComboBoxButton is a RectangularButton shaped like so:

```ts
    Multilink.multilink( [
      this.isWidthResizableProperty,
      this.isHeightResizableProperty,
      this.layoutSizeProperty
    ], ( isWidthSizable, isHeightSizable, layoutSize ) => {
      if ( isWidthSizable || isHeightSizable ) {
        buttonBackground.shape = createButtonShape(
          isWidthSizable ? layoutSize.width - this.maxLineWidth : buttonWidth,
          isHeightSizable ? layoutSize.height - this.maxLineWidth : buttonHeight,
          options );
      }
```

Is this an appropriate place for this workaround?  What about in RectangularButton.createButtonShape?  Our sims have 14 calls to `roundedRectangleWithRadii`.  Do any of them them not want this workaround/guard?

**Comment by jonathanolson** [comment]
Adjusted createButtonShape above.

I'm going to adjust the implementation of the workaround for now.

The following currently NaNs out because of divisions by zero:

```js
kite.Shape.roundedRectangleWithRadii( 0, 0, 100, 100, { topLeft: 0, topRight: 0, bottomLeft: 70, bottomRight: 70 } );
```

The following currently generates a circle (when it really shouldn't, the topLeft/topRight shouldn't be adjusted to 50 each):
```js
kite.Shape.roundedRectangleWithRadii( 0, 0, 100, 100, { topLeft: 1, topRight: 1, bottomLeft: 70, bottomRight: 70 } );
```

**Comment by samreid** [comment]
I'm happy with moving the guards further out, like you did in https://github.com/phetsims/sun/commit/71fcdf55ac92538ff5002470edc44794f84fff91, and making kite assertions only.

Also, in https://github.com/phetsims/kite/commit/154190932bc754506ee6693d0ec8542d4b159ad3 I wanted to ask about 

```ts
if ( topSum > width && topSum > 0 ) {
// ...
if ( bottomSum > width && bottomSum > 0 ) {

// etc.
```
Do we know that width and height are >=0 in this context?  Should that be checked/asserted/enforced?

**Comment by jonathanolson** [comment]
> Do we know that width and height are >=0 in this context? Should that be checked/asserted/enforced?

Yes, that is enforced by assertions (at least currently).

**Comment by samreid** [comment]
Looks good to me, thanks. Closing.
